// Static interests list - no need to fetch from backend
export const INTERESTS_LIST = [
    { id: 'gaming', name: 'Gaming' },
    { id: 'music', name: 'Music' },
    { id: 'art', name: 'Art' },
    { id: 'technology', name: 'Technology' },
    { id: 'sports', name: 'Sports' },
    { id: 'photography', name: 'Photography' },
    { id: 'cooking', name: 'Cooking' },
    { id: 'fitness', name: 'Fitness' },
    { id: 'reading', name: 'Reading' },
    { id: 'movies', name: 'Movies' },
    { id: 'anime', name: 'Anime' },
    { id: 'coding', name: 'Coding' },
    { id: 'design', name: 'Design' },
    { id: 'writing', name: 'Writing' },
    { id: 'travel', name: 'Travel' },
    { id: 'fashion', name: 'Fashion' },
    { id: 'science', name: 'Science' },
    { id: 'history', name: 'History' },
    { id: 'languages', name: 'Languages' },
    { id: 'business', name: 'Business' },
    { id: 'marketing', name: 'Marketing' },
    { id: 'education', name: 'Education' },
    { id: 'health', name: 'Health' },
    { id: 'meditation', name: 'Meditation' },
    { id: 'yoga', name: 'Yoga' },
    { id: 'dance', name: 'Dance' },
    { id: 'theater', name: 'Theater' },
    { id: 'comedy', name: 'Comedy' },
    { id: 'podcasts', name: 'Podcasts' },
    { id: 'streaming', name: 'Streaming' },
    { id: 'youtube', name: 'YouTube' },
    { id: 'twitch', name: 'Twitch' },
    { id: 'discord', name: 'Discord' },
    { id: 'memes', name: 'Memes' },
    { id: 'crypto', name: 'Cryptocurrency' },
    { id: 'investing', name: 'Investing' },
    { id: 'stocks', name: 'Stocks' },
    { id: 'real-estate', name: 'Real Estate' },
    { id: 'cars', name: 'Cars' },
    { id: 'motorcycles', name: 'Motorcycles' },
    { id: 'aviation', name: 'Aviation' },
    { id: 'space', name: 'Space' },
    { id: 'astronomy', name: 'Astronomy' },
    { id: 'physics', name: 'Physics' },
    { id: 'chemistry', name: 'Chemistry' },
    { id: 'biology', name: 'Biology' },
    { id: 'geology', name: 'Geology' },
    { id: 'environment', name: 'Environment' },
    { id: 'sustainability', name: 'Sustainability' },
    { id: 'gardening', name: 'Gardening' },
    { id: 'diy', name: 'DIY' },
    { id: 'crafts', name: 'Crafts' },
    { id: 'woodworking', name: 'Woodworking' },
    { id: 'electronics', name: 'Electronics' },
    { id: 'robotics', name: 'Robotics' },
    { id: 'ai', name: 'Artificial Intelligence' },
    { id: 'machine-learning', name: 'Machine Learning' },
    { id: 'cybersecurity', name: 'Cybersecurity' },
    { id: 'blockchain', name: 'Blockchain' },
    { id: 'web-development', name: 'Web Development' },
    { id: 'mobile-dev', name: 'Mobile Development' },
    { id: 'game-dev', name: 'Game Development' },
    { id: 'ui-ux', name: 'UI/UX Design' },
    { id: 'graphic-design', name: 'Graphic Design' },
    { id: '3d-modeling', name: '3D Modeling' },
    { id: 'animation', name: 'Animation' },
    { id: 'video-editing', name: 'Video Editing' },
    { id: 'music-production', name: 'Music Production' },
    { id: 'sound-design', name: 'Sound Design' },
    { id: 'photography-editing', name: 'Photo Editing' },
    { id: 'filmmaking', name: 'Filmmaking' },
    { id: 'acting', name: 'Acting' },
    { id: 'voice-acting', name: 'Voice Acting' },
    { id: 'singing', name: 'Singing' },
    { id: 'instruments', name: 'Musical Instruments' },
    { id: 'guitar', name: 'Guitar' },
    { id: 'piano', name: 'Piano' },
    { id: 'drums', name: 'Drums' },
    { id: 'bass', name: 'Bass' },
    { id: 'violin', name: 'Violin' },
    { id: 'chess', name: 'Chess' },
    { id: 'board-games', name: 'Board Games' },
    { id: 'card-games', name: 'Card Games' },
    { id: 'puzzles', name: 'Puzzles' },
    { id: 'esports', name: 'Esports' },
    { id: 'fps', name: 'FPS Games' },
    { id: 'moba', name: 'MOBA Games' },
    { id: 'rpg', name: 'RPG Games' },
    { id: 'strategy', name: 'Strategy Games' },
    { id: 'simulation', name: 'Simulation Games' },
    { id: 'indie-games', name: 'Indie Games' },
    { id: 'retro-gaming', name: 'Retro Gaming' },
    { id: 'vr', name: 'Virtual Reality' },
    { id: 'ar', name: 'Augmented Reality' },
]
